{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: mulegraph-db-secret
type: Opaque
data:
  password: {{ "mulegraph" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mulegraph-neo4j-secret
type: Opaque
data:
  neo4j-password: {{ "mulegraph" | b64enc }}
{{- end }}
